### ISSUE TITLE
Not support Avalon Nano

### ISSUE THREAD

**Issue by jimmysitu** [Canaan-Creative/cgminer-openwrt-packages#8]
I try it on WR703 with a Avalon Nano usb miner, but the miner does not work with this package.
cgminer report connection time out. Any idea?

**Comment by qinfengling** [comment]
@jimmysitu Sorry for long time reply. The current package cann't support Avalon nano. but you can compile it with the follow wiki: https://en.bitcoin.it/wiki/Avalon_nano. There is a few people use it under WR703N(OpenWrt).
